### ISSUE TITLE
Dudas enunciado

### ISSUE THREAD

**Issue by carlsjdh** [ULL-ESIT-INF-DSI-2021/ull-esit-inf-dsi-20-21-prct09-async-fs-process-carlsjdh#1]
@esegredo Buenas tardes Segredo, tengo un par de dudas del enunciado de la práctica 9.
Para hacer los ejercicios 2,3,4 se utiliza `yargs`, sin embargo en la anterior práctica lo que hice fue separar la inclusión de los comandos en `yargs`, es decir:
````typescript
yargs.comand({
.............
}}
````
en un fichero `main-app` que llama a los métodos de una instancia de una clase `Notes`
````typescript
 handler(argv) {
    if (typeof argv.user === 'string' &&
    typeof argv.title === 'string' &&
    typeof argv.color === 'string' &&
    typeof argv.body === 'string') {
      notas.addNotes(
          argv.user,
          argv.title,
          argv.body,
          argv.color,
      );
    }
````  

Ya que `notas` pertenece a la clase `Notes` que implemente en el fichero `Notes`. ¿Debería hacer lo mismo en cada ejercicio?¿ o es más conveniente implementar una clase para los comandos `yargs` que se ejecute con por ejemplo `yargsClass.run()` o seguir con el patrón de un directorio `ejercicio1/main-app` donde implemente los comandos y `ejercicio1/notes` y cree la clase que permita usar la api de `Node`.  

-----------------------------------------------------------------------------------------------------------------------------------------

Otra duda con respecto a los test es si para verificar su uso deberíamos realizar pruebas de que lo ha hecho correctamente (es decir, si tiene que escribir un fichero que lo haga y en el mismo test revisar si existe el fichero) o que el método devuelva `true`, `false` o `undefined`. Esto lo digo ya que con el asincronismo me ha dado problemas para verificar el fichero correctamente (dada la naturaleza del asincronismo) y no me queda claro cual es el mejor método para realizar tests en este entorno.

¡Muchas gracias por su atención!

**Comment by esegredo** [comment]
Hola Carlos, buenos días.

Puedes hacerlo como prefieras. Ambas soluciones me parecen adecuadas, y más teniendo en cuenta que los ejercicios de esta práctica no impliquen el uso de muchos comandos y opciones.

Respecto a las pruebas, en la próxima sesión de teoría veremos como llevar a cabo, por un lado, pruebas funcionales (programas que escribes para comprobar cierta funcionalidad de tu código fuente sin usar un framework como mocha) y, por el otro, pruebas con mocha/chai que permiten comprobar funcionamiento de código asíncrono que hayamos escrito. Estas pruebas, básicamente, se basan en emitir eventos haciendo uso de un objeto EventEmitter para que, luego, el código que hayamos escrito (callbacks, por lo general, en respuesta a esos eventos) pueda ser probado.

Saludos.
 @carlsjdh
