### ISSUE TITLE
Node JS - fs.watch() - Chokidar

### ISSUE THREAD

**Issue by carlsjdh** [ULL-ESIT-INF-DSI-2021/ull-esit-inf-dsi-20-21-prct09-async-fs-process-carlsjdh#2]
Buenas tardes @esegredo, disculpes las molestias, pero cuando estuve probando la función `fs.watch()` me di cuenta que repite el evento dos veces cuando analiza un `archivo`. Buscando información al respecto al parecer dicha función puede repetir en ocasiones eventos que ocurran (en este caso repite el evento `change` razón por la que se repite dos veces), la solución que he visto que proponen consiste en utilizar este módulo llamado `chokidar` [Github de chokidar](https://github.com/paulmillr/chokidar) que en principio solventa todos estos problemas.
De hecho tras utilizarlo, el problema se resuelve:
````typescript
import * as chokidar from 'chokidar';
import {spawn} from 'child_process';


const watcher = chokidar.watch('helloworld.txt');

watcher.on('change', () => {
  const wc = spawn('wc', ['helloworld.txt']);

  let data = '';

  wc.stdout.once('data', (chunk) => data += chunk);

  wc.on('close', () => {
    const wcOutputAsArray = data.split(/\s+/);
    console.log(`File helloworld.txt has ${wcOutputAsArray[1]} lines`);
    console.log(`File helloworld.txt has ${wcOutputAsArray[2]} words`);
    console.log(`File helloworld.txt has ${wcOutputAsArray[3]} characters`);
  });
});
````
¿Habría algún problema en utilizar este módulo para realizar esta práctica o hay alguna forma de solventar el problema del watch perteneciente a node que no estoy contemplando correctamente?

Watch:
````typescript
[~/practicas/P9(main)]$node dist/ejercicio2/app.js
File helloworld.txt has 7 lines
File helloworld.txt has 8 words
File helloworld.txt has 49 characters
File helloworld.txt has 7 lines
File helloworld.txt has 8 words
File helloworld.txt has 49 characters
````

Chokidar:
````typescript
[~/practicas/P9(main)]$node dist/ejercicio2/test.js
File helloworld.txt has 7 lines
File helloworld.txt has 8 words
File helloworld.txt has 49 characters
````

Fuente: [fs.watch fired twice when I change the watched file](https://stackoverflow.com/questions/12978924/fs-watch-fired-twice-when-i-change-the-watched-file)

**Comment by esegredo** [comment]
Hola @carlsjdh , buenas tardes.

Si, si lees la documentación oficial, dependiendo del SO, lo que comentas podría suceder y, de hecho, sucede en Linux. Gracias por la información sobre este paquete, no lo conocía. Claro que puedes utilizarlo, siempre y cuando hagas uso del registro de callbacks que atiendan eventos a través del método on.

Saludos.
